### ISSUE TITLE
More Data Line With Less Wires From Esp32

### ISSUE THREAD

**Issue by ScobbyDoo** [hpwit/FASTLEDVIRTUALDRIVER#2]
ignore this points at initial stage
* Signals' level shifter from esp32 to 74hc595
* Huge Current for led
* Voltage drop

![image](https://user-images.githubusercontent.com/76034619/102186497-b37b6a80-3ed8-11eb-9357-17788bd822de.png)

as per you worked around 74hc595 ,is it possible to drive this kind of setup(256 data line)?

**Comment by hpwit** [comment]
Hello
The idea is good but the issue is the required speed to do so. the maximum output speed in I2s is 20Mhz
to push the 8:1 I am already @19,2Mhz.
regards

**Comment by midikidi** [comment]
Yves, you know better that me but i found this
For more information, see ESP32 Technical Reference Manual > I2S Controller (I2S) > LCD Mode [ PDF ]. For high accuracy clock applications, use the APLL_CLK clock source, which has the frequency range of 16 ~ 128 MHz. You can enable the APLL_CLK clock source by setting i2s_config_t::use_apll to TRUE.

**Comment by hpwit** [comment]
hello
That is the clock I am using already. The issue is not the speed but the fact that at that speed sometimes bits are missed when transmitting. for audio it's not issue but for digital like for the leds then it's a problem. It has also been noticed by other developers. I have at that time studied it
