### ISSUE TITLE
Works with other platform ?

### ISSUE THREAD

**Issue by Kamal-Sonani** [hpwit/FASTLEDVIRTUALDRIVER#3]
Esp8266 

Or avr platform ? 
(Atmega8 or 328)

As your sketch used 2 core esp32 is it compatible with single core processor? 

On avr platform communication through Enc28j60 Ethernet

**Comment by hpwit** [comment]
The virtual driver make use of the i2s of the esp32. So I don’t know for esp8266. I need to look at the i2s of the esp8266. but for sure it could work using the spi. How many strips do you want

**Comment by ScobbyDoo** [comment]
@hpwit did you tried virtual output in esp8266 yet?
I found port masking logic in your code for esp32 (16 parallel output)
which way is quicker for multiple output (as compered direct gpio parallel or virtual driver)

I want to try with artnet OR E1.31 & also with sd card

**Comment by hpwit** [comment]
hello
the virtual driver is made is you want a lot of parallels pins. how many pins do you want ?
I haven't looked at the esp8266 yet
Yves

**Comment by ScobbyDoo** [comment]
I'm trying to drive 8 output with 8 gpio without any other process
I'm getting this type of output on each strip 
**Process 1**
first process data~ for pin1, after that for pin2 & so on
pin1 -----
pin2 _____-----       
pin3 __________-----      
pin4 _______________-----
pin5 ____________________-----       
pin6 _________________________-----  
pin7 ____________________________----- 
pin8 _________________________________-----     

instead of  (Don't know how to drive parallelly as port)
**Process2** by doing this FPS will be increased
pin1 -----
pin2 -----     
pin3 -----     
pin4 -----     
pin5 -----     
pin6 -----     
pin7 -----     
pin8 -----               

i would like to drive 16 output with esp8266 with 4gpio as you did in ESP32 using shift registers 
no matter what FPS i get

**Comment by ScobbyDoo** [comment]
i want to drive 16 parallel with esp8266 
nearly 100 to 150 led on each data line

i want to split leds instead of in serial feed

**Comment by hpwit** [comment]
Hello 
To create the 16 parallel outputs I will need to check for the esp8266. I can do 8 // outputs.

**Comment by ScobbyDoo** [comment]
I tried with i2s but not getting right way to do it , compared with your esp32's logic flow.
direct spi used in SD card (logging data),so I'am trying on Soft SPI
Yes , I stuck at 8266

**Comment by ScobbyDoo** [comment]
can you do it? , I want it desperately 
on payable scale

**Comment by hpwit** [comment]
I will look at it. 
how many // outputs do you need ?

**Comment by ScobbyDoo** [comment]
8 

& 16 if possible

**Comment by ScobbyDoo** [comment]
@hpwit what do yo think?

**Comment by hpwit** [comment]
I will look at it this week in more detailed. I have found an esp8266 in my drawer ;)

**Comment by ScobbyDoo** [comment]
What will be initial setup to drive high speed & time critical virtual pins?

I mean which logic should i try?
Using i2s or simply SPI or using spi & DMA?

**Comment by hpwit** [comment]
I use i2s and dma.

**Comment by ScobbyDoo** [comment]
@hpwit i found some esp8266 in last changes , did it works?

**Comment by ScobbyDoo** [comment]
I checked repo , found some esp8266's revision.
It it working with 595?

**Comment by hpwit** [comment]
Hello
Sorry I was busy with other stuff. NO I haven't looked at it yet
i will soon

**Comment by ScobbyDoo** [comment]
@hpwit & @Kamal-Sonani 

  Is their any option for paid service? I want this very desperately 😅 it will be easy for me , working on this from long time but no luck.

Any help would be great.
Thanks

**Comment by hpwit** [comment]
Hello
I will have a look at it. Why can’t you change to esp32. But I will try to make it work
